import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from '@/components/header/header';
import Footer from '@/components/footer/footer';

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200" />
      </head>
      <body className={'grid grid-rows-[74px_auto_200px] min-h-[calc(100svh_-_8px)] dark ' + inter.className}>
        <Header />
        <main className="flex min-h- flex-col items-center justify-between py-24 px-4 sm:px-24">{children}</main>
        <Footer />
      </body>
    </html>
  );
}
